apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
   name: zone-ru-east-ippool
spec:
   cidr: 192.168.0.0/24
   ipipMode: Always
   natOutgoing: true
   nodeSelector: zone == "ru-east"
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
   name: zone-ru-west-ippool
spec:
   cidr: 192.168.1.0/24
   ipipMode: Always
   natOutgoing: true
   nodeSelector: zone == "ru-west"